### ISSUE TITLE
画像が入ったフォルダをDockのアイコンにドロップしても開けない

### ISSUE THREAD

**Issue by coo-ona** [coo-ona/cooViewer#16]
10.15.2で発生
10.14.5では確認できず

**Comment by u39ueda** [comment]
Info.plist内の `CFBundleTypeOSTypes` が古すぎて認識できていないみたいです。
`CFBundleTypeOSTypes` に `fold` を指定しているのを以下のように `LSItemContentTypes` を使うように修正すればフォルダをドロップできました。

```
<dict>
    <key>CFBundleTypeName</key>
    <string>directory</string>
    <key>CFBundleTypeRole</key>
    <string>Viewer</string>
    <key>LSTypeIsPackage</key>
    <false/>
    <key>LSItemContentTypes</key>
    <array>
        <string>public.directory</string>
    </array>
</dict>
```

`LSItemContentTypes` には UTI を指定するらしく、 `public.directory` か `public.folder` のどちらかを指定すればいいと思います。
`LSItemContentTypes` についてはこちらを参照。
[Information Property List Key Reference](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html)
UTI についてはこちらを参照。
[Introduction to Uniform Type Identifiers Reference](https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/UTIRef/Introduction/Introduction.html)

同じように `CFBundleTypeOSTypes` を使っている`CHcd`も認識できていないと思われます。ComicViewerの何かだとは思いますが、私は使ってないためなんのファイルなのかはわかりませんでした。

**Comment by coo-ona** [comment]
@u39ueda
ありがとうございます！近いうち反映します😄
